spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.127.137:8848

server:
  port: 9091

#端点检查
management:
  endpoints:
    web:
      exposure:
        include: "*"