spring:
  application:
    name: rocketmq-provider
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 192.168.127.142:9876
        # RocketMQ 服务器地址
      bindings:
        # 这里是个 Map 类型参数，{} 为 YAML 中 Map 的行内写法
        output: {destination: test-topic, content-type: application/json}
        output2: {destination: test-topic2, content-type: application/json}
server:
  port: 9093

management:
  endpoints:
    web:
      exposure:
        include: '*'