server:
  port: 8081

spring:
  application:
    name: provider

eureka:
  instance:
    prefer-ip-address: true #注册的时候用ip注册
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
